#:kivy 1.10.0
#: import FadeTransition kivy.uix.screenmanager.FadeTransition
#: import hex kivy.utils.get_color_from_hex
#: import utils kivy.utils


<MyScreenManager>:
    transition: FadeTransition()
    InitScreen:
    HomeScreen:
    ChooseEntityScreen:
    VisualizeSystemScreen:
    MakeSimulation:
    OutputVariableScreen:
    ReformsScreen:
    ExecuteSimulationScreen:
    SelectVariableScreen:
    FormVariableScreen:
